// Code generated by fastgen. DO NOT EDIT.

package bitgroup

import (
	"fmt"
	"github.com/iamd3vil/gofastdecoder/fastcore"
)

// Level is a decoded FAST message/group.
type Level struct {
	UpdateAction uint64
	EntryType    uint64
	EndOfBook    bool
	PriceLevel   uint64
}

// LevelDecoder decodes Level messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type LevelDecoder struct {
	pmap         []byte
	bg_LevelInfo []byte
}

func (d *LevelDecoder) decodeLevel(r *fastcore.Reader, pmArg *fastcore.PMAP, m *Level) error {
	pm := *pmArg
	_ = pm
	{
		bg, err := r.ReadBitGroup(d.bg_LevelInfo)
		if err != nil {
			return err
		}
		d.bg_LevelInfo = bg.Buffer()
		if v, err := bg.ReadBits(2); err != nil {
			return err
		} else {
			m.UpdateAction = v
		}
		if v, err := bg.ReadBits(1); err != nil {
			return err
		} else {
			m.EntryType = v
		}
		if v, err := bg.ReadBits(1); err != nil {
			return err
		} else {
			m.EndOfBook = fastcore.Bool(v)
		}
		if v, err := bg.ReadBits(3); err != nil {
			return err
		} else {
			m.PriceLevel = v
		}
	}
	return nil
}

// Decode decodes one Level message from r into m. Use this when the template
// is already known and the stream carries no template-id framing; otherwise use
// a Router.
func (d *LevelDecoder) Decode(r *fastcore.Reader, m *Level) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	return d.decodeLevel(r, &pm, m)
}

// Reset returns the decoder's dictionary to the undefined state. Call it when a
// FAST dictionary reset occurs (e.g. at the start of each datagram for a feed
// with global dictionary scope).
func (d *LevelDecoder) Reset() {
}

// isFASTMessage marks Level as a Message.
func (*Level) isFASTMessage() {}

// Message is any FAST message decoded by Router in this package.
type Message interface{ isFASTMessage() }

// Router decodes a stream of FAST messages, dispatching on the template id. It
// is reusable; its template-id dictionary and per-template decoders persist
// across messages.
//
// Decode returns a pointer into a per-template struct that Decode REUSES on the
// next call for the same template. The returned Message is therefore only valid
// until the next Decode call: to retain a message, type-assert it and copy the
// value before calling Decode again. This reuse is what keeps decoding
// allocation-free.
type Router struct {
	pmap    []byte
	tidSlot fastcore.UintSlot

	// ResetID is the template id of the feed's FAST reset control message
	// (e.g. 120 for T7 MDI/EMDI). When non-zero and a message with this id is
	// decoded, Router resets all dictionaries and Decode returns (nil, nil).
	// Leave it 0 to treat every id as a regular template.
	ResetID  uint32
	LevelDec LevelDecoder
	LevelMsg Level
}

// Reset returns every dictionary (the template-id dictionary and all per-
// template decoders) to the undefined state.
func (rt *Router) Reset() {
	rt.tidSlot.Reset()
	rt.LevelDec.Reset()
}

// Decode reads and decodes the next message from r. On the FAST reset control
// message (see ResetID) it resets all dictionaries and returns (nil, nil); the
// caller should treat a nil Message as a consumed control message and continue.
func (rt *Router) Decode(r *fastcore.Reader) (Message, error) {
	pm, err := r.ReadPMAP(rt.pmap)
	if err != nil {
		return nil, err
	}
	rt.pmap = pm.Buffer()
	tid, _, err := fastcore.DecodeUint(r, &pm, fastcore.OpCopy, fastcore.W32, false, false, 0, &rt.tidSlot)
	if err != nil {
		return nil, err
	}
	if rt.ResetID != 0 && tid == uint64(rt.ResetID) {
		rt.Reset()
		return nil, nil
	}
	switch tid {
	case 5:
		if err := rt.LevelDec.decodeLevel(r, &pm, &rt.LevelMsg); err != nil {
			return nil, err
		}
		return &rt.LevelMsg, nil
	default:
		return nil, fmt.Errorf("fast: unknown template id %d", tid)
	}
}
