// Code generated by fastgen. DO NOT EDIT.

package bitgroup

import (
	"fmt"
	"github.com/iamd3vil/gofastdecoder/fastcore"
)

// Level is a decoded FAST message/group.
type Level struct {
	UpdateAction uint64
	EntryType    uint64
	EndOfBook    bool
	PriceLevel   uint64
}

// LevelDecoder decodes Level messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type LevelDecoder struct {
	pmap         []byte
	bg_LevelInfo []byte
}

func (d *LevelDecoder) decodeLevel(r *fastcore.Reader, pmArg *fastcore.PMAP, m *Level) error {
	pm := *pmArg
	_ = pm
	{
		bg, err := r.ReadBitGroup(d.bg_LevelInfo)
		if err != nil {
			return err
		}
		d.bg_LevelInfo = bg.Buffer()
		if v, err := bg.ReadBits(2); err != nil {
			return err
		} else {
			m.UpdateAction = v
		}
		if v, err := bg.ReadBits(1); err != nil {
			return err
		} else {
			m.EntryType = v
		}
		if v, err := bg.ReadBits(1); err != nil {
			return err
		} else {
			m.EndOfBook = fastcore.Bool(v)
		}
		if v, err := bg.ReadBits(3); err != nil {
			return err
		} else {
			m.PriceLevel = v
		}
	}
	return nil
}

// Decode decodes one Level message from r into m. Use this when the template
// is already known and the stream carries no template-id framing; otherwise use
// a Router.
func (d *LevelDecoder) Decode(r *fastcore.Reader, m *Level) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	return d.decodeLevel(r, &pm, m)
}

// isFASTMessage marks Level as a Message.
func (*Level) isFASTMessage() {}

// Message is any FAST message decoded by Router in this package.
type Message interface{ isFASTMessage() }

// Router decodes a stream of FAST messages, dispatching on the template id. It
// is reusable; its template-id dictionary and per-template decoders persist
// across messages. Decode returns a pointer to a reused per-template struct, so
// the result is only valid until the next Decode call.
type Router struct {
	pmap     []byte
	tidSlot  fastcore.UintSlot
	LevelDec LevelDecoder
	LevelMsg Level
}

// Decode reads and decodes the next message from r.
func (rt *Router) Decode(r *fastcore.Reader) (Message, error) {
	pm, err := r.ReadPMAP(rt.pmap)
	if err != nil {
		return nil, err
	}
	rt.pmap = pm.Buffer()
	tid, _, err := fastcore.DecodeUint(r, &pm, fastcore.OpCopy, fastcore.W32, false, false, 0, &rt.tidSlot)
	if err != nil {
		return nil, err
	}
	switch tid {
	case 5:
		if err := rt.LevelDec.decodeLevel(r, &pm, &rt.LevelMsg); err != nil {
			return nil, err
		}
		return &rt.LevelMsg, nil
	default:
		return nil, fmt.Errorf("fast: unknown template id %d", tid)
	}
}
