// Code generated by fastgen. DO NOT EDIT.

package multifile

import (
	"fmt"
	"github.com/iamd3vil/gofastdecoder/fastcore"
)

// Header is a decoded FAST message/group.
type Header struct {
	SeqNum uint64
}

// HeaderDecoder decodes Header messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type HeaderDecoder struct {
	pmap           []byte
	s_HeaderSeqNum fastcore.UintSlot
}

func (d *HeaderDecoder) decodeHeader(r *fastcore.Reader, pmArg *fastcore.PMAP, m *Header) error {
	pm := *pmArg
	_ = pm
	if v, present, err := fastcore.DecodeUint(r, &pm, fastcore.OpIncrement, fastcore.W32, false, false, 0, &d.s_HeaderSeqNum); err != nil {
		return err
	} else if present {
		m.SeqNum = v
	}
	return nil
}

// Decode decodes one Header message from r into m. Use this when the template
// is already known and the stream carries no template-id framing; otherwise use
// a Router.
func (d *HeaderDecoder) Decode(r *fastcore.Reader, m *Header) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	return d.decodeHeader(r, &pm, m)
}

// isFASTMessage marks Header as a Message.
func (*Header) isFASTMessage() {}

// Quote is a decoded FAST message/group.
type Quote struct {
	SeqNum uint64
	Price  uint64
}

// QuoteDecoder decodes Quote messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type QuoteDecoder struct {
	pmap          []byte
	s_QuoteSeqNum fastcore.UintSlot
	s_QuotePrice  fastcore.UintSlot
}

func (d *QuoteDecoder) decodeQuote(r *fastcore.Reader, pmArg *fastcore.PMAP, m *Quote) error {
	pm := *pmArg
	_ = pm
	if v, present, err := fastcore.DecodeUint(r, &pm, fastcore.OpIncrement, fastcore.W32, false, false, 0, &d.s_QuoteSeqNum); err != nil {
		return err
	} else if present {
		m.SeqNum = v
	}
	if v, present, err := fastcore.DecodeUint(r, &pm, fastcore.OpCopy, fastcore.W32, false, false, 0, &d.s_QuotePrice); err != nil {
		return err
	} else if present {
		m.Price = v
	}
	return nil
}

// Decode decodes one Quote message from r into m. Use this when the template
// is already known and the stream carries no template-id framing; otherwise use
// a Router.
func (d *QuoteDecoder) Decode(r *fastcore.Reader, m *Quote) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	return d.decodeQuote(r, &pm, m)
}

// isFASTMessage marks Quote as a Message.
func (*Quote) isFASTMessage() {}

// Message is any FAST message decoded by Router in this package.
type Message interface{ isFASTMessage() }

// Router decodes a stream of FAST messages, dispatching on the template id. It
// is reusable; its template-id dictionary and per-template decoders persist
// across messages.
//
// Decode returns a pointer into a per-template struct that Decode REUSES on the
// next call for the same template. The returned Message is therefore only valid
// until the next Decode call: to retain a message, type-assert it and copy the
// value before calling Decode again. This reuse is what keeps decoding
// allocation-free.
type Router struct {
	pmap      []byte
	tidSlot   fastcore.UintSlot
	HeaderDec HeaderDecoder
	HeaderMsg Header
	QuoteDec  QuoteDecoder
	QuoteMsg  Quote
}

// Decode reads and decodes the next message from r.
func (rt *Router) Decode(r *fastcore.Reader) (Message, error) {
	pm, err := r.ReadPMAP(rt.pmap)
	if err != nil {
		return nil, err
	}
	rt.pmap = pm.Buffer()
	tid, _, err := fastcore.DecodeUint(r, &pm, fastcore.OpCopy, fastcore.W32, false, false, 0, &rt.tidSlot)
	if err != nil {
		return nil, err
	}
	switch tid {
	case 200:
		if err := rt.HeaderDec.decodeHeader(r, &pm, &rt.HeaderMsg); err != nil {
			return nil, err
		}
		return &rt.HeaderMsg, nil
	case 10:
		if err := rt.QuoteDec.decodeQuote(r, &pm, &rt.QuoteMsg); err != nil {
			return nil, err
		}
		return &rt.QuoteMsg, nil
	default:
		return nil, fmt.Errorf("fast: unknown template id %d", tid)
	}
}
