// Code generated by fastgen. DO NOT EDIT.

package ext12

import (
	"fmt"
	"github.com/iamd3vil/gofastdecoder/fastcore"
	"time"
)

// Ext is a decoded FAST message/group.
type Ext struct {
	Flag bool
	When time.Time
	Kind ExtKind
}

// ExtDecoder decodes Ext messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type ExtDecoder struct {
	pmap      []byte
	s_ExtFlag fastcore.UintSlot
	s_ExtWhen fastcore.IntSlot
	s_ExtKind fastcore.UintSlot
}

func (d *ExtDecoder) decodeExt(r *fastcore.Reader, pmArg *fastcore.PMAP, m *Ext) error {
	pm := *pmArg
	_ = pm
	if v, present, err := fastcore.DecodeUintNone(r, false); err != nil {
		return err
	} else if present {
		m.Flag = fastcore.Bool(v)
	}
	if v, present, err := fastcore.DecodeInt(r, &pm, fastcore.OpNone, fastcore.W64, false, false, 0, &d.s_ExtWhen); err != nil {
		return err
	} else if present {
		m.When = fastcore.TimestampUTC(v, fastcore.UnitSecond)
	}
	if v, present, err := fastcore.DecodeUintNone(r, false); err != nil {
		return err
	} else if present {
		m.Kind = ExtKind(v)
	}
	return nil
}

// Decode decodes one Ext message from r into m. Use this when the template
// is already known and the stream carries no template-id framing; otherwise use
// a Router.
func (d *ExtDecoder) Decode(r *fastcore.Reader, m *Ext) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	return d.decodeExt(r, &pm, m)
}

// Reset returns the decoder's dictionary to the undefined state. Call it when a
// FAST dictionary reset occurs (e.g. at the start of each datagram for a feed
// with global dictionary scope).
func (d *ExtDecoder) Reset() {
	d.s_ExtFlag.Reset()
	d.s_ExtWhen.Reset()
	d.s_ExtKind.Reset()
}

// isFASTMessage marks Ext as a Message.
func (*Ext) isFASTMessage() {}

// ExtKind is a generated FAST enum/set type. Constants hold the wire-encoded value.
type ExtKind uint64

const (
	ExtKindA ExtKind = 0
	ExtKindB ExtKind = 1
	ExtKindC ExtKind = 2
)

// Message is any FAST message decoded by Router in this package.
type Message interface{ isFASTMessage() }

// Router decodes a stream of FAST messages, dispatching on the template id. It
// is reusable; its template-id dictionary and per-template decoders persist
// across messages.
//
// Decode returns a pointer into a per-template struct that Decode REUSES on the
// next call for the same template. The returned Message is therefore only valid
// until the next Decode call: to retain a message, type-assert it and copy the
// value before calling Decode again. This reuse is what keeps decoding
// allocation-free.
type Router struct {
	pmap    []byte
	tidSlot fastcore.UintSlot

	// ResetID is the template id of the feed's FAST reset control message
	// (e.g. 120 for T7 MDI/EMDI). When non-zero and a message with this id is
	// decoded, Router resets all dictionaries and Decode returns (nil, nil).
	// Leave it 0 to treat every id as a regular template.
	ResetID uint32
	ExtDec  ExtDecoder
	ExtMsg  Ext
}

// Reset returns every dictionary (the template-id dictionary and all per-
// template decoders) to the undefined state.
func (rt *Router) Reset() {
	rt.tidSlot.Reset()
	rt.ExtDec.Reset()
}

// Decode reads and decodes the next message from r. On the FAST reset control
// message (see ResetID) it resets all dictionaries and returns (nil, nil); the
// caller should treat a nil Message as a consumed control message and continue.
func (rt *Router) Decode(r *fastcore.Reader) (Message, error) {
	pm, err := r.ReadPMAP(rt.pmap)
	if err != nil {
		return nil, err
	}
	rt.pmap = pm.Buffer()
	tid, _, err := fastcore.DecodeUint(r, &pm, fastcore.OpCopy, fastcore.W32, false, false, 0, &rt.tidSlot)
	if err != nil {
		return nil, err
	}
	if rt.ResetID != 0 && tid == uint64(rt.ResetID) {
		rt.Reset()
		return nil, nil
	}
	switch tid {
	case 3:
		if err := rt.ExtDec.decodeExt(r, &pm, &rt.ExtMsg); err != nil {
			return nil, err
		}
		return &rt.ExtMsg, nil
	default:
		return nil, fmt.Errorf("fast: unknown template id %d", tid)
	}
}
