// Code generated by fastgen. DO NOT EDIT.

package ext12

import (
	"github.com/iamd3vil/gofastdecoder/fastcore"
	"time"
)

// Ext is a decoded FAST message/group.
type Ext struct {
	Flag bool
	When time.Time
	Kind uint64
}

// ExtDecoder decodes Ext messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type ExtDecoder struct {
	pmap      []byte
	s_ExtFlag fastcore.UintSlot
	s_ExtWhen fastcore.IntSlot
	s_ExtKind fastcore.UintSlot
}

func (d *ExtDecoder) decodeExt(r *fastcore.Reader, m *Ext) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	if v, present, err := fastcore.DecodeUint(r, &pm, fastcore.OpNone, false, false, 0, &d.s_ExtFlag); err != nil {
		return err
	} else if present {
		m.Flag = fastcore.Bool(v)
	}
	if v, present, err := fastcore.DecodeInt(r, &pm, fastcore.OpNone, false, false, 0, &d.s_ExtWhen); err != nil {
		return err
	} else if present {
		m.When = fastcore.TimestampUTC(v, fastcore.UnitSecond)
	}
	if v, present, err := fastcore.DecodeUint(r, &pm, fastcore.OpNone, false, false, 0, &d.s_ExtKind); err != nil {
		return err
	} else if present {
		m.Kind = v
	}
	return nil
}

// Decode decodes one Ext message from r into m.
func (d *ExtDecoder) Decode(r *fastcore.Reader, m *Ext) error {
	return d.decodeExt(r, m)
}
