// Code generated by fastgen. DO NOT EDIT.

package rich

import (
	"fmt"
	"github.com/iamd3vil/gofastdecoder/fastcore"
)

// MarketDataStats is a decoded FAST message/group.
type MarketDataStats struct {
	BidCount uint64
	Payload  []byte
}

// MarketDataEntriesElem is a decoded FAST message/group.
type MarketDataEntriesElem struct {
	Action    uint64
	EntryType string
	EntryPx   fastcore.Decimal
	Size      uint64
}

// MarketData is a decoded FAST message/group.
type MarketData struct {
	SeqNum      uint64
	SendingTime uint64
	Symbol      string
	Price       fastcore.Decimal
	Stats       MarketDataStats
	Entries     []MarketDataEntriesElem
}

// MarketDataDecoder decodes MarketData messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type MarketDataDecoder struct {
	pmap                             []byte
	pmap_MarketDataStats             []byte
	pmap_MarketDataEntriesElem       []byte
	s_MarketDataSeqNum               fastcore.UintSlot
	s_MarketDataSendingTime          fastcore.UintSlot
	s_MarketDataSymbol               fastcore.BytesSlot
	s_MarketDataPrice                fastcore.DecimalSlot
	s_MarketDataEntriesLen           fastcore.UintSlot
	s_MarketDataStatsBidCount        fastcore.UintSlot
	s_MarketDataStatsPayload         fastcore.BytesSlot
	s_MarketDataEntriesElemAction    fastcore.UintSlot
	s_MarketDataEntriesElemEntryType fastcore.BytesSlot
	s_MarketDataEntriesElemEntryPx   fastcore.DecimalSlot
	s_MarketDataEntriesElemSize      fastcore.UintSlot
}

func (d *MarketDataDecoder) decodeMarketData(r *fastcore.Reader, pmArg *fastcore.PMAP, m *MarketData) error {
	pm := *pmArg
	_ = pm
	if v, present, err := fastcore.DecodeUintNone(r, false); err != nil {
		return err
	} else if present {
		m.SeqNum = v
	}
	if v, present, err := fastcore.DecodeUintNone(r, false); err != nil {
		return err
	} else if present {
		m.SendingTime = v
	}
	if v, present, err := fastcore.DecodeBytes(r, &pm, fastcore.OpNone, fastcore.ASCIIKind, false, false, nil, &d.s_MarketDataSymbol); err != nil {
		return err
	} else if present {
		m.Symbol = string(v)
	}
	if v, present, err := fastcore.DecodeDecimal(r, &pm, fastcore.OpNone, false, false, fastcore.Decimal{Mant: 0, Exp: 0}, &d.s_MarketDataPrice); err != nil {
		return err
	} else if present {
		m.Price = v
	}
	if err := d.decodeMarketDataStats(r, &m.Stats); err != nil {
		return err
	}

	{
		n, present, err := fastcore.DecodeUintNone(r, false)
		if err != nil {
			return err
		}
		if present {
			if cap(m.Entries) < int(n) {
				m.Entries = make([]MarketDataEntriesElem, n)
			} else {
				m.Entries = m.Entries[:n]
			}
			for i := range m.Entries {
				if err := d.decodeMarketDataEntriesElem(r, &m.Entries[i]); err != nil {
					return err
				}
			}
		} else {
			m.Entries = m.Entries[:0]
		}
	}
	return nil
}
func (d *MarketDataDecoder) decodeMarketDataStats(r *fastcore.Reader, m *MarketDataStats) error {
	pm, err := r.ReadPMAP(d.pmap_MarketDataStats)
	if err != nil {
		return err
	}
	d.pmap_MarketDataStats = pm.Buffer()
	if v, present, err := fastcore.DecodeUintNone(r, false); err != nil {
		return err
	} else if present {
		m.BidCount = v
	}
	if v, present, err := fastcore.DecodeBytes(r, &pm, fastcore.OpNone, fastcore.ByteVectorKind, false, false, nil, &d.s_MarketDataStatsPayload); err != nil {
		return err
	} else if present {
		m.Payload = v
	}
	return nil
}
func (d *MarketDataDecoder) decodeMarketDataEntriesElem(r *fastcore.Reader, m *MarketDataEntriesElem) error {
	pm, err := r.ReadPMAP(d.pmap_MarketDataEntriesElem)
	if err != nil {
		return err
	}
	d.pmap_MarketDataEntriesElem = pm.Buffer()
	if v, present, err := fastcore.DecodeUintNone(r, false); err != nil {
		return err
	} else if present {
		m.Action = v
	}
	if v, present, err := fastcore.DecodeBytes(r, &pm, fastcore.OpNone, fastcore.ASCIIKind, false, false, nil, &d.s_MarketDataEntriesElemEntryType); err != nil {
		return err
	} else if present {
		m.EntryType = string(v)
	}
	if v, present, err := fastcore.DecodeDecimal(r, &pm, fastcore.OpNone, false, false, fastcore.Decimal{Mant: 0, Exp: 0}, &d.s_MarketDataEntriesElemEntryPx); err != nil {
		return err
	} else if present {
		m.EntryPx = v
	}
	if v, present, err := fastcore.DecodeUintNone(r, false); err != nil {
		return err
	} else if present {
		m.Size = v
	}
	return nil
}

// Decode decodes one MarketData message from r into m. Use this when the template
// is already known and the stream carries no template-id framing; otherwise use
// a Router.
func (d *MarketDataDecoder) Decode(r *fastcore.Reader, m *MarketData) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	return d.decodeMarketData(r, &pm, m)
}

// Reset returns the decoder's dictionary to the undefined state. Call it when a
// FAST dictionary reset occurs (e.g. at the start of each datagram for a feed
// with global dictionary scope).
func (d *MarketDataDecoder) Reset() {
	d.s_MarketDataSeqNum.Reset()
	d.s_MarketDataSendingTime.Reset()
	d.s_MarketDataSymbol.Reset()
	d.s_MarketDataPrice.Reset()
	d.s_MarketDataEntriesLen.Reset()
	d.s_MarketDataStatsBidCount.Reset()
	d.s_MarketDataStatsPayload.Reset()
	d.s_MarketDataEntriesElemAction.Reset()
	d.s_MarketDataEntriesElemEntryType.Reset()
	d.s_MarketDataEntriesElemEntryPx.Reset()
	d.s_MarketDataEntriesElemSize.Reset()
}

// isFASTMessage marks MarketData as a Message.
func (*MarketData) isFASTMessage() {}

// Message is any FAST message decoded by Router in this package.
type Message interface{ isFASTMessage() }

// Router decodes a stream of FAST messages, dispatching on the template id. It
// is reusable; its template-id dictionary and per-template decoders persist
// across messages.
//
// Decode returns a pointer into a per-template struct that Decode REUSES on the
// next call for the same template. The returned Message is therefore only valid
// until the next Decode call: to retain a message, type-assert it and copy the
// value before calling Decode again. This reuse is what keeps decoding
// allocation-free.
type Router struct {
	pmap    []byte
	tidSlot fastcore.UintSlot

	// ResetID is the template id of the feed's FAST reset control message
	// (e.g. 120 for T7 MDI/EMDI). When non-zero and a message with this id is
	// decoded, Router resets all dictionaries and Decode returns (nil, nil).
	// Leave it 0 to treat every id as a regular template.
	ResetID       uint32
	MarketDataDec MarketDataDecoder
	MarketDataMsg MarketData
}

// Reset returns every dictionary (the template-id dictionary and all per-
// template decoders) to the undefined state.
func (rt *Router) Reset() {
	rt.tidSlot.Reset()
	rt.MarketDataDec.Reset()
}

// Decode reads and decodes the next message from r. On the FAST reset control
// message (see ResetID) it resets all dictionaries and returns (nil, nil); the
// caller should treat a nil Message as a consumed control message and continue.
func (rt *Router) Decode(r *fastcore.Reader) (Message, error) {
	pm, err := r.ReadPMAP(rt.pmap)
	if err != nil {
		return nil, err
	}
	rt.pmap = pm.Buffer()
	tid, _, err := fastcore.DecodeUint(r, &pm, fastcore.OpCopy, fastcore.W32, false, false, 0, &rt.tidSlot)
	if err != nil {
		return nil, err
	}
	if rt.ResetID != 0 && tid == uint64(rt.ResetID) {
		rt.Reset()
		return nil, nil
	}
	switch tid {
	case 100:
		if err := rt.MarketDataDec.decodeMarketData(r, &pm, &rt.MarketDataMsg); err != nil {
			return nil, err
		}
		return &rt.MarketDataMsg, nil
	default:
		return nil, fmt.Errorf("fast: unknown template id %d", tid)
	}
}
