// Code generated by fastgen. DO NOT EDIT.

package decimalind

import (
	"fmt"
	"github.com/iamd3vil/gofastdecoder/fastcore"
)

// Px is a decoded FAST message/group.
type Px struct {
	Size fastcore.Decimal
}

// PxDecoder decodes Px messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type PxDecoder struct {
	pmap         []byte
	s_PxSizeExp  fastcore.IntSlot
	s_PxSizeMant fastcore.IntSlot
}

func (d *PxDecoder) decodePx(r *fastcore.Reader, pmArg *fastcore.PMAP, m *Px) error {
	pm := *pmArg
	_ = pm
	if exp, present, err := fastcore.DecodeIntCopy(r, &pm, false, false, 0, &d.s_PxSizeExp); err != nil {
		return err
	} else if present {
		mant, _, merr := fastcore.DecodeIntDelta(r, false, false, 0, &d.s_PxSizeMant)
		if merr != nil {
			return merr
		}
		m.Size = fastcore.Decimal{Mant: mant, Exp: int32(exp)}
	}
	return nil
}

// Decode decodes one Px message from r into m. Use this when the template
// is already known and the stream carries no template-id framing; otherwise use
// a Router.
func (d *PxDecoder) Decode(r *fastcore.Reader, m *Px) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	return d.decodePx(r, &pm, m)
}

// Reset returns the decoder's dictionary to the undefined state. Call it when a
// FAST dictionary reset occurs (e.g. at the start of each datagram for a feed
// with global dictionary scope).
func (d *PxDecoder) Reset() {
	d.s_PxSizeExp.Reset()
	d.s_PxSizeMant.Reset()
}

// isFASTMessage marks Px as a Message.
func (*Px) isFASTMessage() {}

// OptPx is a decoded FAST message/group.
type OptPx struct {
	Size    fastcore.Decimal
	HasSize bool
}

// OptPxDecoder decodes OptPx messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type OptPxDecoder struct {
	pmap            []byte
	s_OptPxSizeExp  fastcore.IntSlot
	s_OptPxSizeMant fastcore.IntSlot
}

func (d *OptPxDecoder) decodeOptPx(r *fastcore.Reader, pmArg *fastcore.PMAP, m *OptPx) error {
	pm := *pmArg
	_ = pm
	m.HasSize = false
	if exp, present, err := fastcore.DecodeIntCopy(r, &pm, true, false, 0, &d.s_OptPxSizeExp); err != nil {
		return err
	} else if present {
		mant, _, merr := fastcore.DecodeIntCopy(r, &pm, false, false, 0, &d.s_OptPxSizeMant)
		if merr != nil {
			return merr
		}
		m.Size = fastcore.Decimal{Mant: mant, Exp: int32(exp)}
		m.HasSize = true
	}
	return nil
}

// Decode decodes one OptPx message from r into m. Use this when the template
// is already known and the stream carries no template-id framing; otherwise use
// a Router.
func (d *OptPxDecoder) Decode(r *fastcore.Reader, m *OptPx) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	return d.decodeOptPx(r, &pm, m)
}

// Reset returns the decoder's dictionary to the undefined state. Call it when a
// FAST dictionary reset occurs (e.g. at the start of each datagram for a feed
// with global dictionary scope).
func (d *OptPxDecoder) Reset() {
	d.s_OptPxSizeExp.Reset()
	d.s_OptPxSizeMant.Reset()
}

// isFASTMessage marks OptPx as a Message.
func (*OptPx) isFASTMessage() {}

// Message is any FAST message decoded by Router in this package.
type Message interface{ isFASTMessage() }

// Router decodes a stream of FAST messages, dispatching on the template id. It
// is reusable; its template-id dictionary and per-template decoders persist
// across messages.
//
// Decode returns a pointer into a per-template struct that Decode REUSES on the
// next call for the same template. The returned Message is therefore only valid
// until the next Decode call: to retain a message, type-assert it and copy the
// value before calling Decode again. This reuse is what keeps decoding
// allocation-free.
type Router struct {
	pmap    []byte
	tidSlot fastcore.UintSlot

	// ResetID is the template id of the feed's FAST reset control message
	// (e.g. 120 for T7 MDI/EMDI). When non-zero and a message with this id is
	// decoded, Router resets all dictionaries and Decode returns (nil, nil).
	// Leave it 0 to treat every id as a regular template.
	ResetID  uint32
	PxDec    PxDecoder
	PxMsg    Px
	OptPxDec OptPxDecoder
	OptPxMsg OptPx
}

// Reset returns every dictionary (the template-id dictionary and all per-
// template decoders) to the undefined state.
func (rt *Router) Reset() {
	rt.tidSlot.Reset()
	rt.PxDec.Reset()
	rt.OptPxDec.Reset()
}

// Decode reads and decodes the next message from r. On the FAST reset control
// message (see ResetID) it resets all dictionaries and returns (nil, nil); the
// caller should treat a nil Message as a consumed control message and continue.
func (rt *Router) Decode(r *fastcore.Reader) (Message, error) {
	pm, err := r.ReadPMAP(rt.pmap)
	if err != nil {
		return nil, err
	}
	rt.pmap = pm.Buffer()
	tid, _, err := fastcore.DecodeUint(r, &pm, fastcore.OpCopy, fastcore.W32, false, false, 0, &rt.tidSlot)
	if err != nil {
		return nil, err
	}
	if rt.ResetID != 0 && tid == uint64(rt.ResetID) {
		rt.Reset()
		return nil, nil
	}
	switch tid {
	case 6:
		if err := rt.PxDec.decodePx(r, &pm, &rt.PxMsg); err != nil {
			return nil, err
		}
		return &rt.PxMsg, nil
	case 8:
		if err := rt.OptPxDec.decodeOptPx(r, &pm, &rt.OptPxMsg); err != nil {
			return nil, err
		}
		return &rt.OptPxMsg, nil
	default:
		return nil, fmt.Errorf("fast: unknown template id %d", tid)
	}
}
