// Code generated by fastgen. DO NOT EDIT.

package decimalind

import (
	"fmt"
	"github.com/iamd3vil/gofastdecoder/fastcore"
)

// Px is a decoded FAST message/group.
type Px struct {
	Size fastcore.Decimal
}

// PxDecoder decodes Px messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type PxDecoder struct {
	pmap         []byte
	s_PxSizeExp  fastcore.IntSlot
	s_PxSizeMant fastcore.IntSlot
}

func (d *PxDecoder) decodePx(r *fastcore.Reader, pmArg *fastcore.PMAP, m *Px) error {
	pm := *pmArg
	_ = pm
	if exp, present, err := fastcore.DecodeInt(r, &pm, fastcore.OpCopy, fastcore.W32, false, false, 0, &d.s_PxSizeExp); err != nil {
		return err
	} else if present {
		mant, _, merr := fastcore.DecodeInt(r, &pm, fastcore.OpDelta, fastcore.W64, false, false, 0, &d.s_PxSizeMant)
		if merr != nil {
			return merr
		}
		m.Size = fastcore.Decimal{Mant: mant, Exp: int32(exp)}
	}
	return nil
}

// Decode decodes one Px message from r into m. Use this when the template
// is already known and the stream carries no template-id framing; otherwise use
// a Router.
func (d *PxDecoder) Decode(r *fastcore.Reader, m *Px) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	return d.decodePx(r, &pm, m)
}

// isFASTMessage marks Px as a Message.
func (*Px) isFASTMessage() {}

// OptPx is a decoded FAST message/group.
type OptPx struct {
	Size    fastcore.Decimal
	HasSize bool
}

// OptPxDecoder decodes OptPx messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type OptPxDecoder struct {
	pmap            []byte
	s_OptPxSizeExp  fastcore.IntSlot
	s_OptPxSizeMant fastcore.IntSlot
}

func (d *OptPxDecoder) decodeOptPx(r *fastcore.Reader, pmArg *fastcore.PMAP, m *OptPx) error {
	pm := *pmArg
	_ = pm
	m.HasSize = false
	if exp, present, err := fastcore.DecodeInt(r, &pm, fastcore.OpCopy, fastcore.W32, true, false, 0, &d.s_OptPxSizeExp); err != nil {
		return err
	} else if present {
		mant, _, merr := fastcore.DecodeInt(r, &pm, fastcore.OpCopy, fastcore.W64, false, false, 0, &d.s_OptPxSizeMant)
		if merr != nil {
			return merr
		}
		m.Size = fastcore.Decimal{Mant: mant, Exp: int32(exp)}
		m.HasSize = true
	}
	return nil
}

// Decode decodes one OptPx message from r into m. Use this when the template
// is already known and the stream carries no template-id framing; otherwise use
// a Router.
func (d *OptPxDecoder) Decode(r *fastcore.Reader, m *OptPx) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	return d.decodeOptPx(r, &pm, m)
}

// isFASTMessage marks OptPx as a Message.
func (*OptPx) isFASTMessage() {}

// Message is any FAST message decoded by Router in this package.
type Message interface{ isFASTMessage() }

// Router decodes a stream of FAST messages, dispatching on the template id. It
// is reusable; its template-id dictionary and per-template decoders persist
// across messages.
//
// Decode returns a pointer into a per-template struct that Decode REUSES on the
// next call for the same template. The returned Message is therefore only valid
// until the next Decode call: to retain a message, type-assert it and copy the
// value before calling Decode again. This reuse is what keeps decoding
// allocation-free.
type Router struct {
	pmap     []byte
	tidSlot  fastcore.UintSlot
	PxDec    PxDecoder
	PxMsg    Px
	OptPxDec OptPxDecoder
	OptPxMsg OptPx
}

// Decode reads and decodes the next message from r.
func (rt *Router) Decode(r *fastcore.Reader) (Message, error) {
	pm, err := r.ReadPMAP(rt.pmap)
	if err != nil {
		return nil, err
	}
	rt.pmap = pm.Buffer()
	tid, _, err := fastcore.DecodeUint(r, &pm, fastcore.OpCopy, fastcore.W32, false, false, 0, &rt.tidSlot)
	if err != nil {
		return nil, err
	}
	switch tid {
	case 6:
		if err := rt.PxDec.decodePx(r, &pm, &rt.PxMsg); err != nil {
			return nil, err
		}
		return &rt.PxMsg, nil
	case 8:
		if err := rt.OptPxDec.decodeOptPx(r, &pm, &rt.OptPxMsg); err != nil {
			return nil, err
		}
		return &rt.OptPxMsg, nil
	default:
		return nil, fmt.Errorf("fast: unknown template id %d", tid)
	}
}
