// Code generated by fastgen. DO NOT EDIT.

package templateref

import (
	"fmt"
	"github.com/iamd3vil/gofastdecoder/fastcore"
)

// Common is a decoded FAST message/group.
type Common struct {
	SeqNum uint64
}

// CommonDecoder decodes Common messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type CommonDecoder struct {
	pmap           []byte
	s_CommonSeqNum fastcore.UintSlot
}

func (d *CommonDecoder) decodeCommon(r *fastcore.Reader, pmArg *fastcore.PMAP, m *Common) error {
	pm := *pmArg
	_ = pm
	if v, present, err := fastcore.DecodeUint(r, &pm, fastcore.OpIncrement, fastcore.W32, false, false, 0, &d.s_CommonSeqNum); err != nil {
		return err
	} else if present {
		m.SeqNum = v
	}
	return nil
}

// Decode decodes one Common message from r into m. Use this when the template
// is already known and the stream carries no template-id framing; otherwise use
// a Router.
func (d *CommonDecoder) Decode(r *fastcore.Reader, m *Common) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	return d.decodeCommon(r, &pm, m)
}

// isFASTMessage marks Common as a Message.
func (*Common) isFASTMessage() {}

// Msg is a decoded FAST message/group.
type Msg struct {
	MsgID  uint64
	SeqNum uint64
}

// MsgDecoder decodes Msg messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type MsgDecoder struct {
	pmap        []byte
	s_MsgMsgID  fastcore.UintSlot
	s_MsgSeqNum fastcore.UintSlot
}

func (d *MsgDecoder) decodeMsg(r *fastcore.Reader, pmArg *fastcore.PMAP, m *Msg) error {
	pm := *pmArg
	_ = pm
	if v, present, err := fastcore.DecodeUint(r, &pm, fastcore.OpCopy, fastcore.W32, false, false, 0, &d.s_MsgMsgID); err != nil {
		return err
	} else if present {
		m.MsgID = v
	}
	if v, present, err := fastcore.DecodeUint(r, &pm, fastcore.OpIncrement, fastcore.W32, false, false, 0, &d.s_MsgSeqNum); err != nil {
		return err
	} else if present {
		m.SeqNum = v
	}
	return nil
}

// Decode decodes one Msg message from r into m. Use this when the template
// is already known and the stream carries no template-id framing; otherwise use
// a Router.
func (d *MsgDecoder) Decode(r *fastcore.Reader, m *Msg) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	return d.decodeMsg(r, &pm, m)
}

// isFASTMessage marks Msg as a Message.
func (*Msg) isFASTMessage() {}

// Message is any FAST message decoded by Router in this package.
type Message interface{ isFASTMessage() }

// Router decodes a stream of FAST messages, dispatching on the template id. It
// is reusable; its template-id dictionary and per-template decoders persist
// across messages. Decode returns a pointer to a reused per-template struct, so
// the result is only valid until the next Decode call.
type Router struct {
	pmap      []byte
	tidSlot   fastcore.UintSlot
	CommonDec CommonDecoder
	CommonMsg Common
	MsgDec    MsgDecoder
	MsgMsg    Msg
}

// Decode reads and decodes the next message from r.
func (rt *Router) Decode(r *fastcore.Reader) (Message, error) {
	pm, err := r.ReadPMAP(rt.pmap)
	if err != nil {
		return nil, err
	}
	rt.pmap = pm.Buffer()
	tid, _, err := fastcore.DecodeUint(r, &pm, fastcore.OpCopy, fastcore.W32, false, false, 0, &rt.tidSlot)
	if err != nil {
		return nil, err
	}
	switch tid {
	case 100:
		if err := rt.CommonDec.decodeCommon(r, &pm, &rt.CommonMsg); err != nil {
			return nil, err
		}
		return &rt.CommonMsg, nil
	case 7:
		if err := rt.MsgDec.decodeMsg(r, &pm, &rt.MsgMsg); err != nil {
			return nil, err
		}
		return &rt.MsgMsg, nil
	default:
		return nil, fmt.Errorf("fast: unknown template id %d", tid)
	}
}
