// Code generated by fastgen. DO NOT EDIT.

package simple

import (
	"github.com/iamd3vil/gofastdecoder/fastcore"
)

// Test is a decoded FAST message/group.
type Test struct {
	Field1 uint64
	Field2 uint64
	Field3 uint64
}

// TestDecoder decodes Test messages. Reuse it across messages; its
// dictionary state persists as the field operators require.
type TestDecoder struct {
	pmap         []byte
	s_TestField1 fastcore.UintSlot
	s_TestField2 fastcore.UintSlot
	s_TestField3 fastcore.UintSlot
}

func (d *TestDecoder) decodeTest(r *fastcore.Reader, m *Test) error {
	pm, err := r.ReadPMAP(d.pmap)
	if err != nil {
		return err
	}
	d.pmap = pm.Buffer()
	if v, present, err := fastcore.DecodeUint(r, &pm, fastcore.OpCopy, false, false, 0, &d.s_TestField1); err != nil {
		return err
	} else if present {
		m.Field1 = v
	}
	if v, present, err := fastcore.DecodeUint(r, &pm, fastcore.OpCopy, false, false, 0, &d.s_TestField2); err != nil {
		return err
	} else if present {
		m.Field2 = v
	}
	if v, present, err := fastcore.DecodeUint(r, &pm, fastcore.OpCopy, false, false, 0, &d.s_TestField3); err != nil {
		return err
	} else if present {
		m.Field3 = v
	}
	return nil
}

// Decode decodes one Test message from r into m.
func (d *TestDecoder) Decode(r *fastcore.Reader, m *Test) error {
	return d.decodeTest(r, m)
}
